### ISSUE TITLE
Auto Scroll up and down

### ISSUE THREAD

**Issue by CarmenLexa** [mbalabash/puppeteer-autoscroll-down#11]
I'm using the plugin, but I need it to scroll up as well, and I do it this way

`await scrollPageToBottom(page,{delay:500,size:-600});`

but it does not return the promise, could you add a new function to scroll up please?

**Comment by mbalabash** [comment]
Hey @CarmenLexa!
Yes, I think it could be useful. Do you want to prepare PR?

**Comment by CarmenLexa** [comment]
hi guy, of course it would be useful to have a more natural scrolling motion with up and down movement.
could you help us with that please

**Comment by mbalabash** [comment]
@CarmenLexa Do you want to implement this feature and submit PR?

**Comment by mbalabash** [comment]
If not, I could do it on next week

**Comment by CarmenLexa** [comment]
I can't implement it on my own, you could do it since you have the idea :D

**Comment by mbalabash** [comment]
Released in `puppeteer-autoscroll-down@1.1.0`. 
You can see usage example [here](https://github.com/mbalabash/puppeteer-autoscroll-down#not-only-scroll-to-the-bottom-but-there-is-also-function-for-scroll-to-the-top).

**Comment by mbalabash** [comment]
fyi: @CarmenLexa
